{
  "hash": "8751f86670977ef78946e8671604b813",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exploring the Simpson's Paradox Within the Penguin Dataset\"\nformat:\n  html:\n    code-fold: true\n    code-summary: \"Show the code\"\n    toc: true\n    toc-location: left\n    toc-title: \" \"\n    number-sections: true\n# editor: source\nfig-cap-location: margin\n---\n\n# Introduction\nThis page is an output from the '[Productive R Workflow](https://www.productive-r-workflow.com/r/module2/format-text-with-markdown)' course, by Yann Holtz. \n\n::: {.callout}\nNote that I used Positron as my IDE, rather than R Studio, so there are some differences.\n:::\n\n# Data and Libraries\n\nGotta load some libraries before we go...\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(palmerpenguins)\nlibrary(hrbrthemes)\nlibrary(patchwork)\nlibrary(tinytable)\n```\n:::\n\n\nThen we need to have some data to work with. We cleaned the data in a previous step and created a couple of functions.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsource(file = \"R/functions.r\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# read clean data\n\ndf_clean_data <- readRDS(file = \"input/df_clean_data.rds\")\n```\n:::\n\n\nA bit of context for what we are talking about.\n\n![What are the Bill Measurements?](assets/culmen_depth.png){width=300}\n\n# Exploring the data\n\nHere is a scatterplot of all the data comparing bill length with bill depth. What do you notice? What do you wonder?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_clean_data |> \n  ggplot(\n    aes(x = bill_length_mm, y = bill_depth_mm)\n  ) +\n    geom_point(color=\"#69b3a2\") +\n    labs(\n      x = \"Bill Length (mm)\",\n      y = \"Bill Depth (mm)\",\n      title = paste(\"Bill length x Bill Depth\")\n    ) + \n  theme_ipsum()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/plot_length_v_depth-1.png){width=672}\n:::\n:::\n\n\n## Averages by Species\n\nThe following tables show the average bill length and depth by species.\n\n\n::: {.cell layout-ncol=\"2\"}\n\n```{.r .cell-code}\naverage_length <- df_clean_data |> \n   group_by(species) |> \n  summarise(average_bill_length = mean(bill_length_mm, na.rm = TRUE))\n\ntt(average_length)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_4lwg6kybs70k6kmb5z8d = TinyTable.createTableFunctions(\"tinytable_4lwg6kybs70k6kmb5z8d\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '3', j: 1 }, { i: '3', j: 2 } ], css_id: 'tinytable_css_ilijm2ajuir5l8xpsxir',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 } ], css_id: 'tinytable_css_l1of4z1wcs61shh2slvk',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_4lwg6kybs70k6kmb5z8d.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_4lwg6kybs70k6kmb5z8d td.tinytable_css_ilijm2ajuir5l8xpsxir, #tinytable_4lwg6kybs70k6kmb5z8d th.tinytable_css_ilijm2ajuir5l8xpsxir {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.1em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_4lwg6kybs70k6kmb5z8d td.tinytable_css_l1of4z1wcs61shh2slvk, #tinytable_4lwg6kybs70k6kmb5z8d th.tinytable_css_l1of4z1wcs61shh2slvk {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_4lwg6kybs70k6kmb5z8d\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">species</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">average_bill_length</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">Adelie</td>\n                  <td data-row=\"1\" data-col=\"2\">38.80872</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">Chinstrap</td>\n                  <td data-row=\"2\" data-col=\"2\">48.83382</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">Gentoo</td>\n                  <td data-row=\"3\" data-col=\"2\">47.50488</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n\n```{.r .cell-code}\nbill_length_chinstrap <- df_clean_data |> \n group_by(species) |> \n  summarise(average_bill_length = mean(bill_length_mm, na.rm = TRUE)) |> \n  filter(species == \"Chinstrap\") |> \n  pull(average_bill_length) |> \n  round(2)\n\n  \naverage_depth <- df_clean_data |> \n group_by(species) |> \n  summarise(average_bill_depth = mean(bill_depth_mm, na.rm = TRUE))\n\ntt(average_depth)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_uy2yguzjvpkqzxov9d74 = TinyTable.createTableFunctions(\"tinytable_uy2yguzjvpkqzxov9d74\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '3', j: 1 }, { i: '3', j: 2 } ], css_id: 'tinytable_css_7sg6znenw5n4dm9ead18',}, \n          { positions: [ { i: '0', j: 1 }, { i: '0', j: 2 } ], css_id: 'tinytable_css_pgh8rzp32n0op09rxi5h',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_uy2yguzjvpkqzxov9d74.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_uy2yguzjvpkqzxov9d74 td.tinytable_css_7sg6znenw5n4dm9ead18, #tinytable_uy2yguzjvpkqzxov9d74 th.tinytable_css_7sg6znenw5n4dm9ead18 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.1em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    #tinytable_uy2yguzjvpkqzxov9d74 td.tinytable_css_pgh8rzp32n0op09rxi5h, #tinytable_uy2yguzjvpkqzxov9d74 th.tinytable_css_pgh8rzp32n0op09rxi5h {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%;  }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_uy2yguzjvpkqzxov9d74\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\">species</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">average_bill_depth</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">Adelie</td>\n                  <td data-row=\"1\" data-col=\"2\">18.34228</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\">Chinstrap</td>\n                  <td data-row=\"2\" data-col=\"2\">18.42059</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">Gentoo</td>\n                  <td data-row=\"3\" data-col=\"2\">14.98211</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n\n```{.r .cell-code}\nbill_depth_chinstrap <- df_clean_data |> \n group_by(species) |> \n  summarise(average_bill_depth = mean(bill_depth_mm, na.rm = TRUE)) |> \n  filter(species == \"Chinstrap\") |> \n  pull(average_bill_depth) |> \n  round(2)\n```\n:::\n\nAs you can see the average bill length for the Chinstrap penguin is 48.83, and the average bill depth for the Chinstrap penguin is 18.42.\n\n## Plotting by Species\n\n\n::: {.cell .fig-cap-location-margin}\n\n```{.r .cell-code}\n# Use function in functions.r\n\np1 <- create_scatterplot(df_clean_data, \"Adelie\", \"#6689c6\") \np2 <- create_scatterplot(df_clean_data, \"Gentoo\", \"#e85252\") \np3 <- create_scatterplot(df_clean_data, \"Chinstrap\", \"#9a6fb0\") \np1 + p2 + p3\n```\n\n::: {.cell-output-display}\n![There is actually a positive correlation when split by species.](index_files/figure-html/unnamed-chunk-1-1.png){width=864}\n:::\n:::\n\n\n\n\n\n### Sample latex\n\n$$E=mc^2$$\n\n# Thank you!\n\nThe `palmerpenguins` package was created and shared by Kristen Gorman, a researcher at the Palmer Station in Antarctica. It contains data about 344 penguins, including three species of penguins on three different islands. The package is licensed under a [CC-0](https://creativecommons.org/public-domain/cc0/) license.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncitation(\"palmerpenguins\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTo cite palmerpenguins in publications use:\n\n  Horst AM, Hill AP, Gorman KB (2020). palmerpenguins: Palmer\n  Archipelago (Antarctica) penguin data. R package version 0.1.0.\n  https://allisonhorst.github.io/palmerpenguins/. doi:\n  10.5281/zenodo.3960218.\n\nA BibTeX entry for LaTeX users is\n\n  @Manual{,\n    title = {palmerpenguins: Palmer Archipelago (Antarctica) penguin data},\n    author = {Allison Marie Horst and Alison Presmanes Hill and Kristen B Gorman},\n    year = {2020},\n    note = {R package version 0.1.0},\n    doi = {10.5281/zenodo.3960218},\n    url = {https://allisonhorst.github.io/palmerpenguins/},\n  }\n```\n\n\n:::\n:::\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}